#!/usr/bin/env bash
set -euo pipefail

# The setup-bazel action writes ~/.bazelrc. That file is shared by the runners,
# so self-hosted Unix jobs use an already downloaded Bazel binary and a job rc
# instead. Never invoke Bazelisk here: it may download a missing version.

repo_root="${GITHUB_WORKSPACE:-$PWD}"
version_file="$repo_root/.bazelversion"
ci_build_root="${CI_BUILD_ROOT:?CI_BUILD_ROOT must be set by setup-ci}"
output_base="${BAZEL_OUTPUT_BASE:?BAZEL_OUTPUT_BASE must be set by setup-ci}"
github_env="${GITHUB_ENV:?GITHUB_ENV must be set by GitHub Actions}"
github_path="${GITHUB_PATH:?GITHUB_PATH must be set by GitHub Actions}"

if [[ "$ci_build_root" == *$'\r'* || "$ci_build_root" == *$'\n'* || "$ci_build_root" == *,* \
  || "$output_base" == *$'\r'* || "$output_base" == *$'\n'* \
  || "${BAZELRC:-}" == *$'\r'* || "${BAZELRC:-}" == *$'\n'* ]]; then
  echo "Cannot configure cached Bazel: unsupported control character or comma in CI path" >&2
  exit 1
fi

if [[ ! -f "$version_file" ]]; then
  echo "Cannot configure cached Bazel: missing $version_file" >&2
  exit 1
fi

if ! expected_version="$(awk 'NF { line = $0; count++ } END { if (count != 1) exit 1; print line }' "$version_file")"; then
  echo "Cannot configure cached Bazel: .bazelversion must contain one version" >&2
  exit 1
fi
if [[ ! "$expected_version" =~ ^[0-9]+\.[0-9]+\.[0-9]+([.-][0-9A-Za-z.-]+)?$ ]]; then
  echo "Cannot configure cached Bazel: unsupported .bazelversion '$expected_version'" >&2
  exit 1
fi

if [[ "$ci_build_root" != /* || "$output_base" != /* ]]; then
  echo "Cannot configure cached Bazel: CI paths must be absolute" >&2
  exit 1
fi

declare -a cache_roots=()
if [[ -n "${BAZELISK_HOME:-}" ]]; then
  cache_roots+=("$BAZELISK_HOME")
fi
if [[ -n "${XDG_CACHE_HOME:-}" ]]; then
  cache_roots+=("$XDG_CACHE_HOME/bazelisk")
fi
cache_roots+=("$HOME/.cache/bazelisk" "$HOME/Library/Caches/bazelisk")

declare -a candidates=()
candidate_count=0
max_candidates=64
for cache_root in "${cache_roots[@]}"; do
  [[ -d "$cache_root/downloads/sha256" ]] || continue
  while IFS= read -r candidate; do
    [[ -n "$candidate" ]] || continue
    if (( candidate_count >= max_candidates )); then
      echo "Cannot configure cached Bazel: more than $max_candidates cached binaries found" >&2
      exit 1
    fi
    candidates+=("$candidate")
    ((candidate_count += 1))
  done < <(
    find "$cache_root/downloads/sha256" \
      -mindepth 3 -maxdepth 3 -type f -perm -100 -name bazel -print 2>/dev/null
  )
done

probe_bazel_version() {
  python3 - "$1" <<'PY'
import subprocess
import sys

try:
    completed = subprocess.run(
        [sys.argv[1], "--ignore_all_rc_files", "--version"],
        capture_output=True,
        check=False,
        text=True,
        timeout=10,
    )
except (OSError, subprocess.TimeoutExpired):
    raise SystemExit(1)

if completed.returncode == 0:
    sys.stdout.write(completed.stdout)
else:
    raise SystemExit(1)
PY
}

validated_binary=""
if (( candidate_count > 0 )); then
  for candidate in "${candidates[@]}"; do
    [[ -x "$candidate" && ! -L "$candidate" ]] || continue
    version_output="$(probe_bazel_version "$candidate" || true)"
    actual_version="$(awk '$1 == "bazel" { print $2; exit }' <<<"$version_output")"
    if [[ "$actual_version" == "$expected_version" ]]; then
      validated_binary="$candidate"
      break
    fi
  done
fi

if [[ -z "$validated_binary" ]]; then
  echo "Cannot configure cached Bazel: no cached binary matches Bazel $expected_version" >&2
  exit 1
fi

bin_dir="$ci_build_root/bin"
mkdir -p "$bin_dir"
shim="$bin_dir/bazel"
cat >"$shim" <<EOF
#!/usr/bin/env bash
exec $(printf '%q' "$validated_binary") "\$@"
EOF
chmod 755 "$shim"

job_rc="$ci_build_root/bazelrc"
output_base_rc="${output_base//\'/\'\\\'\'}"
cat >"$job_rc" <<EOF
# Generated by setup-bazel-ci; this file is job-scoped and never written to HOME.
startup --output_base='$output_base_rc'
EOF

# BAZELRC is read after workspace and HOME rc files. Preserve any caller-supplied
# environment rc and append ours so the job output base wins without hiding it.
if [[ -n "${BAZELRC:-}" ]]; then
  bazelrc_value="$BAZELRC,$job_rc"
else
  bazelrc_value="$job_rc"
fi
{
  printf 'BAZELRC=%s\n' "$bazelrc_value"
  # Keep the existing run_bazel_with_buildbuddy.py resource and lock wrapper
  # in the invocation path while making its Bazel target explicit.
  printf 'CODEX_BAZEL_BIN=%s\n' "$shim"
} >>"$github_env"
printf '%s\n' "$bin_dir" >>"$github_path"

echo "Using cached Bazel $expected_version with job-scoped output base"
