// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutoReviewRunSummary } from "./AutoReviewRunSummary";
import type { AutoReviewStatusCount } from "./AutoReviewStatusCount";

export type AutoReviewSummaryReadResponse = { latest: AutoReviewRunSummary | null, current: AutoReviewRunSummary | null, statusCounts: Array<AutoReviewStatusCount>, };
