// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutoReviewFreshness } from "./AutoReviewFreshness";
import type { AutoReviewRunSource } from "./AutoReviewRunSource";
import type { BackgroundAutoReviewStatus } from "./BackgroundAutoReviewStatus";

export type AutoReviewRunSummary = { runId: string, status: BackgroundAutoReviewStatus, source: AutoReviewRunSource, freshness: AutoReviewFreshness, startedAt: number, completedAt: number | null, model: string | null, errorSummary: string | null, renderedFindings: number, omittedFindings: number, truncated: boolean, content: string, };
