// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutoReviewDispositionActor } from "./AutoReviewDispositionActor";
import type { AutoReviewFindingDisposition } from "./AutoReviewFindingDisposition";

export type AutoReviewFindingDispositionRecord = { disposition: AutoReviewFindingDisposition, actor: AutoReviewDispositionActor, reason: string | null, updatedAt: number, };
