// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutoReviewDetailKind } from "./AutoReviewDetailKind";

export type AutoReviewFindingDetailReadResponse = { runId: string, detailKind: AutoReviewDetailKind, findingId: string | null, findingCount: number, omittedFindings: number, bytes: number, originalBytes: number, maxBytes: number, truncated: boolean, content: string, };
