// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AutoReviewDiagnosticsSummary = { recentRuns: number, inFlightRuns: number, terminalRuns: number, skippedRuns: number, duplicateSkippedRuns: number, supersededRuns: number, failedRuns: number, cancelledRuns: number, lostRuns: number, suppressedStaleRuns: number, compact: string, };
