// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutoReviewFreshness } from "./AutoReviewFreshness";
import type { AutoReviewRunSource } from "./AutoReviewRunSource";
import type { BackgroundAutoReviewStatus } from "./BackgroundAutoReviewStatus";

export type AutoReviewStatusCount = { status: BackgroundAutoReviewStatus, source: AutoReviewRunSource, freshness: AutoReviewFreshness, targetMatches: boolean, count: number, };
