// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutoReviewDispositionAction } from "./AutoReviewDispositionAction";

export type AutoReviewDispositionWriteParams = { threadId: string, runId: string, action: AutoReviewDispositionAction, reason?: string | null, };
