// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AutoReviewFindingDetailReadResponse = { runId: string, findingId: string, bytes: number, originalBytes: number, maxBytes: number, truncated: boolean, content: string, };
