// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AutoReviewUsage = { scopeBytes: number | null, elapsedMs: number | null, totalTokens: number | null, inputTokens: number | null, cachedInputTokens: number | null, outputTokens: number | null, effectiveTotalTokenLimit: number | null, accountingToleranceTokens: number | null, projectedTotalTokens: number | null, requestCount: number | null, retryCount: number | null, toolRegistryTokens: number | null, toolRegistryPrunedCount: number | null, toolOutputTokens: number | null, toolOutputLimitTokens: number | null, responseOutputLimitTokens: number | null, responseOutputReservationTokens: number | null, orchestrationSkillsSuppressed: boolean | null, outputBytes: number | null, findingCount: number | null, };
