// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackgroundAutoReviewControlAction } from "./BackgroundAutoReviewControlAction";
import type { BackgroundAutoReviewControlReason } from "./BackgroundAutoReviewControlReason";

export type BackgroundAutoReviewControlParams = { threadId: string, runId: string, action: BackgroundAutoReviewControlAction, reason: BackgroundAutoReviewControlReason, };
