// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackgroundAutoReviewStatus } from "./BackgroundAutoReviewStatus";
import type { ReviewTarget } from "./ReviewTarget";

export type BackgroundAutoReviewStatusChangedNotification = { threadId: string, runId: string, status: BackgroundAutoReviewStatus, reviewTarget: ReviewTarget, errorSummary: string | null, };
