// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CodeBridgeScreenshotMediaType } from "./CodeBridgeScreenshotMediaType";

export type CodeBridgeScreenshotPayload = { width: number, height: number, mediaType: CodeBridgeScreenshotMediaType, dataBase64: string, };
