// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CodeBridgeConsoleLevel } from "./CodeBridgeConsoleLevel";
import type { CodeBridgeEventKind } from "./CodeBridgeEventKind";

export type CodeBridgeSubscriptionFilter = { levels: Array<CodeBridgeConsoleLevel>, eventKinds: Array<CodeBridgeEventKind>, clientIds: Array<string>, };
