// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExternalAgentSettingOrigin } from "./ExternalAgentSettingOrigin";

export type ExternalAgentSelectorState = { selector: string, discovered: boolean, model: string | null, explicitOnly: boolean, enabled: boolean, enabledOrigin: ExternalAgentSettingOrigin | null, defaultModel: string | null, defaultModelOrigin: ExternalAgentSettingOrigin | null, defaultEffort: string | null, defaultEffortOrigin: ExternalAgentSettingOrigin | null, };
