// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExternalAgentAuthState } from "./ExternalAgentAuthState";
import type { ExternalAgentCapabilityFailure } from "./ExternalAgentCapabilityFailure";
import type { ExternalAgentCapabilityFreshness } from "./ExternalAgentCapabilityFreshness";
import type { ExternalAgentCapabilitySource } from "./ExternalAgentCapabilitySource";
import type { ExternalAgentInstallState } from "./ExternalAgentInstallState";
import type { ExternalAgentSelectorState } from "./ExternalAgentSelectorState";

export type ExternalAgentProviderCapabilities = { family: string, command: string, install: ExternalAgentInstallState, auth: ExternalAgentAuthState, cliVersion: string | null, supportsModelSelection: boolean, supportsEffortSelection: boolean, effortLevels: Array<string>, source: ExternalAgentCapabilitySource, freshness: ExternalAgentCapabilityFreshness, observedAt: bigint | null, failure: ExternalAgentCapabilityFailure | null, selectors: Array<ExternalAgentSelectorState>, };
