// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExternalAgentCapabilitiesRefreshStatus } from "./ExternalAgentCapabilitiesRefreshStatus";
import type { ExternalAgentProviderCapabilities } from "./ExternalAgentProviderCapabilities";

export type ExternalAgentCapabilitiesUpdatedNotification = { refreshId: string, status: ExternalAgentCapabilitiesRefreshStatus, providers: Array<ExternalAgentProviderCapabilities>, };
