// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExternalAgentCapabilityFailureKind } from "./ExternalAgentCapabilityFailureKind";

export type ExternalAgentCapabilityFailure = { kind: ExternalAgentCapabilityFailureKind, message: string, };
