// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";
import type { ProjectValidationSkipReason } from "./ProjectValidationSkipReason";
import type { ProjectValidationStatus } from "./ProjectValidationStatus";

/**
 * One completed project-validation command execution. An actionable first execution may be
 * followed by one bounded correction cycle and a second completion notification.
 */
export type ProjectValidationCompletedNotification = { threadId: string, turnId: string, command: Array<string>, commandTruncated: boolean, cwd?: AbsolutePathBuf, status: ProjectValidationStatus, skipReason: ProjectValidationSkipReason | null, changedFileCount: number | null, exitCode?: number, output: string, outputTruncated: boolean, durationMs: bigint, };
