// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";
import type { ProjectValidationStatus } from "./ProjectValidationStatus";

export type ProjectValidationCompletedNotification = { threadId: string, turnId: string, command: Array<string>, cwd?: AbsolutePathBuf, status: ProjectValidationStatus, exitCode?: number, output: string, outputTruncated: boolean, durationMs: bigint, };
