// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Compiled identity for the running app-server binary.
 *
 * `initialize.userAgent` remains the negotiated HTTP user-agent string for
 * compatibility. This struct carries the immutable build identity consumers
 * should use when comparing backend versions or release provenance.
 */
export type ServerBuildInfo = { schemaVersion: number, version: string, sourceCommit: string, dirtyState: string, buildProfile: string, buildChannel: string, };
