// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Structured provenance for a thread started by an external orchestrator.
 *
 * These fields are descriptive metadata only. Runtime authorization and
 * product filtering must continue to use server-side policy and `source`.
 */
export type SessionProvenance = { requestId: string | null, repository: string | null, issueNumber: number | null, issueUrl: string | null, source: string | null, origin: string | null, };
