// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Client-supplied provenance for a thread started by an external orchestrator.
 *
 * This request shape intentionally keeps nested fields optional so clients can
 * submit partial descriptive metadata without sending explicit nulls.
 */
export type SessionProvenanceParams = { requestId?: string | null, repository?: string | null, issueNumber?: number | null, issueUrl?: string | null, source?: string | null, origin?: string | null, };
