#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
artifact_root="${CODEX_LAB_DEVELOPER_ARTIFACTS_ROOT:-/Volumes/Developer-Artifacts}"
apply=0

usage() {
	cat <<USAGE
Usage: scripts/local/setup-artifacts.sh [--apply] [--artifact-root DIR]

Generate local artifact-routing config for this checkout. The default mode is a
dry run and prints the user.bazelrc that would be written plus the opt-in local
environment command for package-manager, temp, and optional sccache routing.

Options:
  --apply              Write user.bazelrc.
  --artifact-root DIR  Artifact volume root. Default: CODEX_LAB_DEVELOPER_ARTIFACTS_ROOT
                       or /Volumes/Developer-Artifacts.
  -h, --help           Show this help.
USAGE
}

while [[ $# -gt 0 ]]; do
	case "$1" in
	--apply)
		apply=1
		;;
	--artifact-root)
		if [[ $# -lt 2 ]]; then
			echo "error: --artifact-root requires a directory" >&2
			usage >&2
			exit 2
		fi
		artifact_root="$2"
		shift
		;;
	-h | --help)
		usage
		exit 0
		;;
	*)
		echo "error: unknown option: $1" >&2
		usage >&2
		exit 2
		;;
	esac
	shift
done

case "$artifact_root" in
/*) ;;
*)
	echo "error: artifact root must be an absolute path: $artifact_root" >&2
	exit 2
	;;
esac

artifact_root="${artifact_root%/}"
bazel_root="$artifact_root/local/codex-lab/bazel"
user_bazelrc="$repo_root/user.bazelrc"

render_user_bazelrc() {
	cat <<BAZELRC
# Generated by scripts/local/setup-artifacts.sh.
# This file is gitignored and machine-local.
common --disk_cache=$bazel_root/disk-cache
common --repo_contents_cache=$bazel_root/repo-contents-cache
common --repository_cache=$bazel_root/repository-cache
common --output_base=$bazel_root/output-base
common --output_user_root=$bazel_root/output-user-root
BAZELRC
}

if [[ "$apply" -eq 1 ]]; then
	if [[ ! -d "$artifact_root" || ! -w "$artifact_root" ]]; then
		echo "error: artifact root is not mounted or writable: $artifact_root" >&2
		exit 1
	fi
	mkdir -p "$bazel_root"
	render_user_bazelrc >"$user_bazelrc"
	printf 'Wrote %s\n' "$user_bazelrc"
	"$repo_root/scripts/local/artifact-env.sh" --artifact-root "$artifact_root" >/dev/null
	printf 'Prepared package-manager and temp directories under %s/local/codex-lab.\n' "$artifact_root"
else
	printf 'Dry run. Re-run with --apply to write %s.\n\n' "$user_bazelrc"
	render_user_bazelrc
	printf '\nTo route local package-manager caches, temp output, and optional sccache for a shell, run:\n'
	printf '  eval "$(%q --artifact-root %q)"\n' "$repo_root/scripts/local/artifact-env.sh" "$artifact_root"
fi
