pub mod auth;
pub mod auth_accounts;
pub mod auth_env_telemetry;
pub mod auth_profiles;
pub mod token_data;

mod device_code_auth;
mod pkce;
mod server;

pub use codex_client::BuildCustomCaTransportError as BuildLoginHttpClientError;
pub use codex_config::types::AuthCredentialsStoreMode;
pub use device_code_auth::DeviceCode;
pub use device_code_auth::complete_device_code_login;
pub use device_code_auth::request_device_code;
pub use device_code_auth::run_device_code_login;
pub use server::LoginServer;
pub use server::ServerOptions;
pub use server::ShutdownHandle;
pub use server::run_login_server;

pub use auth::AuthConfig;
pub use auth::AuthDotJson;
pub use auth::AuthManager;
pub use auth::AuthManagerConfig;
pub use auth::CLIENT_ID;
pub use auth::CODEX_ACCESS_TOKEN_ENV_VAR;
pub use auth::CODEX_API_KEY_ENV_VAR;
pub use auth::CodexAuth;
pub use auth::ExternalAuth;
pub use auth::ExternalAuthChatgptMetadata;
pub use auth::ExternalAuthRefreshContext;
pub use auth::ExternalAuthRefreshReason;
pub use auth::ExternalAuthTokens;
pub use auth::OPENAI_API_KEY_ENV_VAR;
pub use auth::REFRESH_TOKEN_URL_OVERRIDE_ENV_VAR;
pub use auth::REVOKE_TOKEN_URL_OVERRIDE_ENV_VAR;
pub use auth::RefreshTokenError;
pub use auth::UnauthorizedRecovery;
pub use auth::default_client;
pub use auth::enforce_login_restrictions;
pub use auth::load_auth_dot_json;
pub use auth::login_with_access_token;
pub use auth::login_with_api_key;
pub use auth::logout;
pub use auth::logout_with_revoke;
pub use auth::read_codex_access_token_from_env;
pub use auth::read_openai_api_key_from_env;
pub use auth::save_auth;
pub use auth_accounts::StoredAccount;
pub use auth_accounts::find_account;
pub use auth_accounts::get_active_account_id;
pub use auth_accounts::list_accounts;
pub use auth_accounts::remove_account;
pub use auth_accounts::remove_account_matching_credentials;
pub use auth_accounts::set_active_account_id;
pub use auth_accounts::update_account_last_refresh;
pub use auth_accounts::upsert_api_key_account;
pub use auth_accounts::upsert_chatgpt_account;
pub use auth_env_telemetry::AuthEnvTelemetry;
pub use auth_env_telemetry::collect_auth_env_telemetry;
pub use auth_profiles::AuthProfileEntry;
pub use auth_profiles::AuthProfileMetadata;
pub use auth_profiles::AuthProfilesFile;
pub use auth_profiles::list_auth_profiles;
pub use auth_profiles::profile_home;
pub use auth_profiles::record_auth_profile_login;
pub use auth_profiles::remove_auth_profile_metadata;
pub use auth_profiles::upsert_auth_profile;
pub use auth_profiles::validate_profile_name;
pub use token_data::TokenData;
