// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "./AbsolutePathBuf";
import type { ServerBuildInfo } from "./v2/ServerBuildInfo";

export type InitializeResponse = { userAgent: string,
/**
 * Actual compiled identity for the running app-server binary.
 */
serverBuild: ServerBuildInfo | null,
/**
 * Absolute path to the server's $CODEX_LAB_HOME directory.
 */
codexHome: AbsolutePathBuf,
/**
 * Platform family for the running app-server target, for example
 * `"unix"` or `"windows"`.
 */
platformFamily: string,
/**
 * Operating system for the running app-server target, for example
 * `"macos"`, `"linux"`, or `"windows"`.
 */
platformOs: string, };
